import type { Metadata } from "next";
import localFont from 'next/font/local'
import { NeueHaas } from '@/utils/fonts'

import Header from '@/components/Header'
import Footer from '@/components/Footer'

import "./globals.css";

export const metadata: Metadata = {
  title: "Jack Whiting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-grey-400 text-black min-h-screen flex flex-col ${NeueHaas.className}`}>

        <main className="flex-grow flex flex-col pt-[161px]">
          <Header />
          {children}
          <Footer />
        </main>
        

      </body>
    </html>
  );
}
