import { NeueHaas } from "@/utils/fonts"
import type { Metadata } from "next"
import Footer from "@/components/Footer"
import Header from "@/components/Header"
import { getApiQuery } from "@/utils/getApiQuery"
import { GLOBAL_QUERY } from "@/queries/globals"

import "./globals.css"

export const metadata: Metadata = {
  title: "Jack Whiting",
  description: "Generated by create next app",
}

async function getData() {
  const { totalProjects, footer } = await getApiQuery(GLOBAL_QUERY, {})

  return {
    totalProjects,
    footer,
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { totalProjects, footer } = await getData()

  return (
    <html lang="en">
      <body
        className={`bg-grey-400 text-black-700 min-h-screen flex flex-col ${NeueHaas.className}`}
      >
        <main className="flex-grow flex flex-col pt-[161px]">
          <Header totalProjects={totalProjects} />
          {children}
          <Footer {...footer} />
        </main>
      </body>
    </html>
  )
}
